In [1]:
library(SNITCH)
library(Seurat)
library(dbscan)     
library(ggplot2)
library(ggrepel)
library(dplyr)
library(tibble)
library(factoextra)

## run SNITCH on gene expression across pseudotime

In [6]:
seurat2 = readRDS('./410.DifferentialExpressions/01.ExN/111.PFC_bigger/metacells_ExN_seurat2.RDS')
meta = read.csv('./410.DifferentialExpressions/01.ExN/111.PFC_bigger/OBS_forseurat_l23_metacells2.csv')

In [16]:
genes_expr = read.csv('./400.Metacell/01.ExN//12.PFC_bigger/all_genes_expression_metacellNorm50k.csv', row.names = 1)
colnames(genes_expr) <- paste0("snitch_", colnames(genes_expr))
meta = cbind(meta, genes_expr)

                [,1]       [,2]      [,3]       [,4]      [,5]
Set_1_GP_factor  2.1711287 2.3424293  1.2485105 1.8571155  2.2022128
Set_2_GP_factor -0.3171863 0.7539624 -0.1987924 0.3005028 -0.1951377
Set_3_GP_factor  1.0588503 0.8522418  1.4459311 0.7416224  1.0677713
Set_4_GP_factor  2.3321095 1.8280572  0.9086739 1.7009563  2.0698776
Set_5_GP_factor  2.0310453 1.4421524  1.4141572 1.9942268  2.0441927
Set_6_GP_factor  2.0785674 1.2741577  2.1139698 1.5134505  1.6914163
                [,6]        [,7]       [,8]       [,9]       [,10]      [,11]
Set_1_GP_factor  1.53628875  2.6984010  1.3024491  1.4151235  2.7653943 ⋯
Set_2_GP_factor -0.08580618 -0.7384751 -0.4012618 -0.2688875 -1.2028934 ⋯
Set_3_GP_factor  0.88496914  0.8613027  1.0768160  0.8512512  0.9590387 ⋯
Set_4_GP_factor  1.50916937  1.8038210  1.1818698  1.4450725  1.9178056 ⋯
Set_5_GP_factor  2.19389962  1.7211764  1.5535058  1.7848946  1.5860099 ⋯
Set_6_GP_factor  1.90136478  1.5105452  2.3092629  2.1239440  1.5288405 ⋯
                [,12]      [,13]      [,14]      [,15]      [,16]
Set_1_GP_factor  1.8872197  1.1195472  1.3390165  1.1662972  0.9586632
Set_2_GP_factor -0.2621482 -0.6733572 -0.2540828 -0.7062438 -0.1535388
Set_3_GP_factor  0.5713133  1.0027409  0.9732916  1.1180784  0.7772247
Set_4_GP_factor  1.3609641  0.6686943  1.6456976  0.7446095  0.8920190
Set_5_GP_factor  1.9664898  1.2631282  1.3685424  1.4083406  1.2198365
Set_6_GP_factor  1.4289610  2.2309316  2.3473705  2.3203374  1.6938854
                [,17]      [,18]      [,19]      [,20]      [,21]
Set_1_GP_factor  1.3214048  1.3331529  0.6852345  2.6784754  1.2136194
Set_2_GP_factor -0.4989207 -0.9657312 -0.7496694 -0.9070184 -0.6595594
Set_3_GP_factor  1.1019839  0.6102497  0.5170245  0.8596238  1.0635917
Set_4_GP_factor  1.7128831  1.3473780  0.4223234  1.6354456  1.0835042
Set_5_GP_factor  1.3172717  1.4408186  1.0134854  1.5166482  1.7355415
Set_6_GP_factor  2.5649698  1.4583459  1.7048503  1.4525093  2.4725568

In [18]:

# Select all columns starting with "mean_TOTAL_GP_"
mean_cols <- grep("GP_factor", colnames(meta), value = TRUE)

# Create a data frame with only these columns
mean_df <- meta[, mean_cols]
mean_df = t(mean_df)

In [19]:
count_df  <- mean_df
scaled_data <- prepare_data(data = t(count_df), age = seurat2@meta.data$pseudotime_rank)

In [21]:
classified_cpgs <- run_parallel_classification(dat_scaled = scaled_data$dat_scaled, 
                                               age = scaled_data$Age, 
                                               ages_grid = scaled_data$ages_grid, 
                                              covariates = meta$total_cells)

In [22]:
non_linear_cpgs <- classified_cpgs[grep("NL", classified_cpgs$classification),]$CpG
nl_smooth_rows  <- classified_cpgs[grep("NL", classified_cpgs$classification),]
nl_smooth       <- do.call(rbind, nl_smooth_rows$Predictions)
rownames(nl_smooth) <- non_linear_cpgs

# Perform FPCA
fpca_results <- perform_fpca(nl_var_smooth = nl_smooth, ages_grid = scaled_data$ages_grid)

# Plot FPCA results (files are saved by the function)
plot_fpca_results(fpca_results, ages_grid = scaled_data$ages_grid)

Warning message in sqrt(Eigen$values):
“NaNs produced”

In [25]:
class_work <- classified_cpgs
nl_mask    <- class_work$classification == "NL"

In [27]:
hdb_fit <- hdbscan(as.matrix(fpca_results$scores), minPts = 2)
pred_hdb <- paste0("NL_", hdb_fit$cluster)
cw_hdb <- class_work; cw_hdb$classification[nl_mask] <- pred_hdb
cw_hdb2 <- cw_hdb[ , !(names(cw_hdb) %in% "Predictions")]
cw_hdb2

     CpG              lm_pval      lm_coef       dbic_lg      bp_pval
BP   Set_1_GP_factor  1.034158e-03  3.339161e-04 36.368303566 6.534896e-02
BP1  Set_2_GP_factor  5.257424e-46 -1.385215e-03 -8.764288119 6.999093e-02
BP2  Set_3_GP_factor  1.538190e-02  2.469049e-04 -0.008390483 3.575628e-09
BP3  Set_4_GP_factor  7.949598e-01  2.651532e-05 34.578867851 3.553575e-01
BP4  Set_5_GP_factor  3.979966e-02  2.095491e-04  5.422037144 7.015280e-01
BP5  Set_6_GP_factor  1.388008e-01 -1.509568e-04 -5.691176674 1.448929e-03
BP6  Set_7_GP_factor  4.979600e-14  7.582539e-04 -6.409111651 1.302429e-02
BP7  Set_8_GP_factor  1.821576e-01 -1.360679e-04 -6.478549983 2.887698e-01
BP8  Set_9_GP_factor  3.251982e-12 -7.026351e-04 35.817530416 1.569035e-01
BP9  Set_10_GP_factor 1.214100e-01 -1.579458e-04 -0.302998728 6.674327e-01
BP10 Set_11_GP_factor 2.695239e-02  2.254534e-04 40.968957893 2.042033e-01
BP11 Set_12_GP_factor 9.565157e-01  5.563475e-06 -0.046372797 5.525213e-04
BP12 Set_13_GP_factor 1.424634e-02  2.497223e-04 26.171027761 8.519423e-03
BP13 Set_14_GP_factor 4.475964e-01 -7.747570e-05  0.205058323 8.269464e-04
BP14 Set_15_GP_factor 2.717461e-03 -3.052391e-04 -4.799113377 5.743877e-01
BP15 Set_16_GP_factor 1.631572e-02  2.447218e-04 10.206785109 3.191676e-02
BP16 Set_17_GP_factor 3.022552e-03 -3.019362e-04 -6.002964078 6.398525e-01
BP17 Set_18_GP_factor 5.798287e-04 -3.500908e-04 -4.087018209 6.707413e-03
BP18 Set_19_GP_factor 5.282988e-37  1.248248e-03 -5.112669574 7.182344e-01
BP19 Set_20_GP_factor 4.661441e-03  2.881541e-04 -0.012613544 8.570798e-05
BP20 Set_21_GP_factor 2.118281e-10  6.419636e-04 -5.625979541 8.649667e-02
     white_pval   gam_edf  gam_refdf gam_pval     adj_lm       adj_white
BP   1.828698e-01 3.284800 3.723352  0.000000e+00 1.551238e-02 1.000000e+00
BP1  3.449728e-11 3.067469 3.556076  0.000000e+00 1.104059e-44 7.244428e-10
BP2  2.704429e-08 1.000679 1.001358  1.542242e-02 1.567098e-01 5.408858e-07
BP3  6.488812e-01 3.360121 3.774178  0.000000e+00 1.000000e+00 1.000000e+00
BP4  1.615988e-02 2.720071 3.237930  1.193947e-04 2.785976e-01 1.817151e-01
BP5  3.361584e-03 2.391674 2.895820  4.486353e-02 7.284599e-01 5.042375e-02
BP6  9.816498e-06 2.788807 3.305018  0.000000e+00 9.461240e-13 1.865135e-04
BP7  2.798276e-01 1.991082 2.446418  1.800101e-01 7.286306e-01 1.000000e+00
BP8  2.273093e-01 3.405801 3.802978  0.000000e+00 5.853568e-11 1.000000e+00
BP9  4.411849e-01 2.638259 3.155813  2.904188e-03 7.284599e-01 1.000000e+00
BP10 1.514293e-02 3.361002 3.774748  0.000000e+00 2.156191e-01 1.817151e-01
BP11 1.546148e-03 1.003867 1.007722  9.781664e-01 1.000000e+00 2.473836e-02
BP12 2.240862e-02 3.649657 3.927301  0.000000e+00 1.567098e-01 2.236278e-01
BP13 3.525141e-03 2.609962 3.126878  6.065185e-03 1.000000e+00 5.042375e-02
BP14 7.907587e-01 2.397758 2.902424  1.260291e-03 3.804446e-02 1.000000e+00
BP15 3.170091e-04 3.140023 3.615058  3.948921e-06 1.567098e-01 5.389155e-03
BP16 2.236278e-02 2.769238 3.286104  1.384938e-03 3.929317e-02 2.236278e-01
BP17 2.385921e-02 1.432026 1.738038  2.530256e-03 9.277259e-03 2.236278e-01
BP18 1.365672e-02 2.613544 3.130556  0.000000e+00 1.056598e-35 1.775374e-01
BP19 1.460394e-04 1.000962 1.001924  4.683595e-03 5.593729e-02 2.628709e-03
BP20 1.423582e-01 2.449978 2.958759  0.000000e+00 3.601078e-09 9.965076e-01
     classification adj_gam
BP   NL_0           0.000000e+00
BP1  LD             0.000000e+00
BP2  VI             6.168966e-02
BP3  NL_0           0.000000e+00
BP4  NL_0           1.313342e-03
BP5  NC             1.345906e-01
BP6  LI             0.000000e+00
BP7  NC             3.600201e-01
BP8  NL_0           0.000000e+00
BP9  NC             2.032932e-02
BP10 NL_0           0.000000e+00
BP11 NC             9.781664e-01
BP12 NL_0           0.000000e+00
BP13 NC             3.032592e-02
BP14 NC             1.260291e-02
BP15 NL_0           4.738705e-05
BP16 NC             1.260291e-02
BP17 LD             2.024205e-02
BP18 LI             0.000000e+00
BP19 VI             2.810157e-02
BP20 LI             0.000000e+00

In [1]:
# try to find optimal number of clusters 

p_elbow <- fviz_nbclust(fpca_results$scores, kmeans, k.max = 6, method = "wss") +
  labs(title = "Elbow Method for K-Means",
       x = "Number of Clusters (K)",
       y = "Total Within-Cluster Sum of Squares (WCSS)") +
  theme_minimal()
ggplot2::ggsave("SNITCH_kmeans_elbow_2.pdf", p_elbow, width = 6, height = 4)

k_opt  <- 5
km_fit <- kmeans(as.matrix(fpca_results$scores), centers = k_opt, nstart = 2)
pred_km <- paste0("NL_", km_fit$cluster)
cw_km <- class_work; cw_km$classification[nl_mask] <- pred_km
# df_comp <- dplyr::bind_rows(df_comp, add_metrics(cw_km$classification, "SNITCH + K-Means"))

ERROR: Error in fviz_nbclust(fpca_results$scores, kmeans, k.max = 6, method = "wss"): could not find function "fviz_nbclust"

In [33]:
cw_km2 <- cw_km[ , !(names(cw_km) %in% "Predictions")]
cw_km2_sorted<- cw_km2[order(cw_km2$adj_gam),]
subset(cw_km2_sorted, classification != "NC")

     CpG              lm_pval      lm_coef       dbic_lg      bp_pval
BP   Set_1_GP_factor  1.034158e-03  3.339161e-04 36.368303566 6.534896e-02
BP1  Set_2_GP_factor  5.257424e-46 -1.385215e-03 -8.764288119 6.999093e-02
BP3  Set_4_GP_factor  7.949598e-01  2.651532e-05 34.578867851 3.553575e-01
BP6  Set_7_GP_factor  4.979600e-14  7.582539e-04 -6.409111651 1.302429e-02
BP8  Set_9_GP_factor  3.251982e-12 -7.026351e-04 35.817530416 1.569035e-01
BP10 Set_11_GP_factor 2.695239e-02  2.254534e-04 40.968957893 2.042033e-01
BP12 Set_13_GP_factor 1.424634e-02  2.497223e-04 26.171027761 8.519423e-03
BP18 Set_19_GP_factor 5.282988e-37  1.248248e-03 -5.112669574 7.182344e-01
BP20 Set_21_GP_factor 2.118281e-10  6.419636e-04 -5.625979541 8.649667e-02
BP15 Set_16_GP_factor 1.631572e-02  2.447218e-04 10.206785109 3.191676e-02
BP4  Set_5_GP_factor  3.979966e-02  2.095491e-04  5.422037144 7.015280e-01
BP17 Set_18_GP_factor 5.798287e-04 -3.500908e-04 -4.087018209 6.707413e-03
BP19 Set_20_GP_factor 4.661441e-03  2.881541e-04 -0.012613544 8.570798e-05
BP2  Set_3_GP_factor  1.538190e-02  2.469049e-04 -0.008390483 3.575628e-09
     white_pval   gam_edf  gam_refdf gam_pval     adj_lm       adj_white
BP   1.828698e-01 3.284800 3.723352  0.000000e+00 1.551238e-02 1.000000e+00
BP1  3.449728e-11 3.067469 3.556076  0.000000e+00 1.104059e-44 7.244428e-10
BP3  6.488812e-01 3.360121 3.774178  0.000000e+00 1.000000e+00 1.000000e+00
BP6  9.816498e-06 2.788807 3.305018  0.000000e+00 9.461240e-13 1.865135e-04
BP8  2.273093e-01 3.405801 3.802978  0.000000e+00 5.853568e-11 1.000000e+00
BP10 1.514293e-02 3.361002 3.774748  0.000000e+00 2.156191e-01 1.817151e-01
BP12 2.240862e-02 3.649657 3.927301  0.000000e+00 1.567098e-01 2.236278e-01
BP18 1.365672e-02 2.613544 3.130556  0.000000e+00 1.056598e-35 1.775374e-01
BP20 1.423582e-01 2.449978 2.958759  0.000000e+00 3.601078e-09 9.965076e-01
BP15 3.170091e-04 3.140023 3.615058  3.948921e-06 1.567098e-01 5.389155e-03
BP4  1.615988e-02 2.720071 3.237930  1.193947e-04 2.785976e-01 1.817151e-01
BP17 2.385921e-02 1.432026 1.738038  2.530256e-03 9.277259e-03 2.236278e-01
BP19 1.460394e-04 1.000962 1.001924  4.683595e-03 5.593729e-02 2.628709e-03
BP2  2.704429e-08 1.000679 1.001358  1.542242e-02 1.567098e-01 5.408858e-07
     classification adj_gam
BP   NL_1           0.000000e+00
BP1  LD             0.000000e+00
BP3  NL_1           0.000000e+00
BP6  LI             0.000000e+00
BP8  NL_3           0.000000e+00
BP10 NL_1           0.000000e+00
BP12 NL_1           0.000000e+00
BP18 LI             0.000000e+00
BP20 LI             0.000000e+00
BP15 NL_2           4.738705e-05
BP4  NL_1           1.313342e-03
BP17 LD             2.024205e-02
BP19 VI             2.810157e-02
BP2  VI             6.168966e-02

In [100]:
write.csv(cw_km2, 'classification_modules_SNITCH.csv')